### ISSUE TITLE
{"error":"invalid authorization","key":"unauthorization","errno":401001}

### ISSUE THREAD

**Issue by heartasice** [pili-engineering/pili-sdk-java#30]
Dear Engineering Team,
I 'v check out the latest version ,I got qiniu AppKey & Secret, and it's work fine in uploading files. but not working here .

 the error code when I run the Example.java

{"error":"invalid authorization","key":"unauthorization","errno":401001}

Thanks & Regards

Eric

**Comment by longbai** [comment]
You need apply pili service by https://pili.qiniu.com/
