### ISSUE TITLE
关于Hub包的问题

### ISSUE THREAD

**Issue by sky-syk** [pili-engineering/pili-sdk-java#61]
import com.pili.Hub;我目前是这个包，而github是这个包com.pili.qiniu.Hub,是更新版本了么，hub的listlive方法等都没有

**Comment by sky-syk** [comment]
解决了，谢谢回答，就是版本的问题@longbai

**Comment by longbai** [comment]
maven 有 v1, v2 两个版本， com.pili.hub 是 v1 的分支
